FROM node:22-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN npm install

RUN npm run db:generate

COPY . .

RUN npm install

RUN cd ./apps/web && npm run build

EXPOSE 3002

CMD ["npm","run","start:frontend"]
