FROM node:22-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/http-server ./apps/http-server

RUN npm install

RUN npm run db:generate

COPY . .

RUN npm install 

RUN cd ./apps/http-server && npm run build && cd ../..

EXPOSE 4002

CMD ["npm","run","start:backend"]